### ISSUE TITLE
Next JS build not compiling

### ISSUE THREAD

**Issue by brikiernan** [fortana-co/react-dropzone-uploader#192]
Hello,

I replaced react-dropzone with react-dropzone-uploader in a nextjs app and the code won't compile now.

From the error I'm getting I though maybe in my .tsconfig the skipLibCheck was not set to true but it is.

I'm not sure why typescript is checking your package?

Any ideas on this?

Thanks! Brian

```
Failed to compile.

./node_modules/react-dropzone-uploader/dist/Dropzone.tsx:504:44
Type error: Object is of type 'unknown'.

  502 |       params = await getUploadParams(fileWithMeta)
  503 |     } catch (e) {
> 504 |       console.error('Error Upload Params', e.stack)
      |                                            ^
  505 |     }
  506 |     if (params === null) return
  507 |     const { url, method = 'POST', body, fields = {}, headers = {}, meta: extraMeta = {} } = params


```

**Comment by brikiernan** [comment]
This issue https://github.com/fortana-co/react-dropzone-uploader/issues/179#issue-1101934418 had the solution for me.

I had to set the "useUnknownInCatchVariables": true in my .tsconfig

**Comment by prmichaelsen** [comment]
not a fan of the solution above because it may swallow other important errors in your project. see https://github.com/fortana-co/react-dropzone-uploader/issues/108#issuecomment-1083621257

i want to fix this myself but to be honest im not one hundred percent sure what's going on in their packaging scripts
